version: '3'

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080"
  client:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
