services:
  letterboxd-blend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      PORT: ${PORT}
      RPDB_API_KEY: ${RPDB_API_KEY}
      VITE_API_ENDPOINT: ${VITE_API_ENDPOINT}
      VITE_SOCKET_ENDPOINT: ${VITE_SOCKET_ENDPOINT}
      VITE_BASE_URL: ${VITE_BASE_URL}